### ISSUE TITLE
Windows Logs submit to Log Viewer in UTC time, but aren't converted to local time of Viewer in v2.15+

### ISSUE THREAD

**Issue by hjoh95** [GoogleCloudPlatform/ops-agent#1076]
**Describe the bug**
Windows Logs submit to Log Viewer in UTC time, but aren't converted to local time of Viewer in v2.15+

**Example**
Screenshot taken at 12:30pm CST - Windows Event Logs (Channel: Application) stop at 6:30am "CST" (UTC-6:00)
![image](https://user-images.githubusercontent.com/104024476/216132334-f97621de-7c17-453c-b7dd-aa0fa904174f.png)

**To Reproduce**
Install any agent version above v2.14. Windows Event Logs will start showing up in Logs Viewer with an unadjusted timestamp.

**Expected behavior**
Windows Event Logs should be converted from UTC to the timezone of Log Viewer. This issue is not present in v2.14

**Environment (please complete the following information):**
 - Windows Server 2019 Datacenter
 - Ops Agent version v2.15+

**Comment by braydonk** [comment]
Thanks for making an issue. This is a known problem; we've resolved it upstream, but currently we are blocked from upgrading Fluent Bit due to some issues we're actively investigating. Whenever we are able to upgrade the version of Fluent Bit, this issue should be resolved.

**Comment by hjoh95** [comment]
Love to hear it. Is there an estimated timeline on the being available?

**Comment by braydonk** [comment]
Unfortunately not right now; we really want to upgrade, so we're doing everything we can to get to the bottom of the issues but we haven't figured out enough to make an estimate. It's a top priority for us at the moment though.

**Comment by jefferbrecht** [comment]
This is now fixed in [2.27.0](https://github.com/GoogleCloudPlatform/ops-agent/releases/tag/2.27.0).
