### ISSUE TITLE
`FbMetricsPortErr` when restarting the Ops Agent 2.25.1

### ISSUE THREAD

**Issue by franciscovalentecastro** [GoogleCloudPlatform/ops-agent#1088]
**Describe the bug**
The following `false positive` can present sometimes when the Ops Agent version 2.25.1 is restarted :
```
Ports Check - Result: FAIL, Error code: FbMetricsPortErr, Failure: Port 20202 needed for Ops Agent self metrics is unavailable., Solution: Verify that port 20202 is open., Resource: https://cloud.google.com/logging/docs/agent/ops-agent/tr
oubleshooting
```

This error message can be safely ignored in Ops Agent version 2.25.1. 

A solution for this error is being worked on : https://github.com/GoogleCloudPlatform/ops-agent/pull/1082 .

**To Reproduce**
Steps to reproduce the behaviour:
1. Start a GCE VM with a linux distribution image.
2. Install Ops Agent version '2.25.1'
3. Restart the agent
4. See this error sometimes appears. It is only informational.
```
Ports Check - Result: FAIL, Error code: FbMetricsPortErr, Failure: Port 20202 needed for Ops Agent self metrics is unavailable., Solution: Verify that port 20202 is open., Resource: https://cloud.google.com/logging/docs/agent/ops-agent/tr
oubleshooting
```

**Expected behavior**
In most cases, when the VM is correctly configured with not ports conflict the message should be : `Ports Check - Result: PASS`

**Environment (please complete the following information):**
 - Ops Agent version `2.25.1` in a Linux distribution.

**Additional context**

**Comment by jefferbrecht** [comment]
This is now fixed: https://github.com/GoogleCloudPlatform/ops-agent/releases/tag/2.26.0
