### ISSUE TITLE
Unable to install ops agent on GCE Ubuntu 20.04 and 22.04

### ISSUE THREAD

**Issue by haim0n** [GoogleCloudPlatform/ops-agent#1130]
**Describe the bug**
The google-cloud-ops-agent fails to install on GCE instance.

**To Reproduce**
1. Start a GCE VM with image projects/ubuntu-os-cloud/global/images/ubuntu-2004-focal-v20230213
2. Install Ops Agent latest version  following the steps 
```
curl -O https://packages.cloud.google.com/apt/doc/apt-key.gpg && sudo apt-key add apt-key.gpg
curl -sSO https://dl.google.com/cloudagents/add-google-cloud-ops-agent-repo.sh
sudo bash add-google-cloud-ops-agent-repo.sh --also-install
```
4. See error: 
`gpg: no valid OpenPGP data found.`   <-- this is because https://packages.cloud.google.com/apt/doc/apt-key.gpg returns 500 Server error.
Followed by installation error:
```
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
Reading package lists... Done
W: GPG error: https://packages.cloud.google.com/apt google-cloud-ops-agent-focal-all InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B53DC80D13EDEF05
E: The repository 'https://packages.cloud.google.com/apt google-cloud-ops-agent-focal-all InRelease' is not signed.
```

**Expected behavior**
The ops agent installed 

**Environment (please complete the following information):**
 - VM distro / OS: Ubuntu 20.04 and Ubuntu 22.04
 - Ops Agent version : all versions
 - Ops Agent configuration
 - Ops Agent log

**Additional context**
on Feb 26  it was working fine

**Comment by braydonk** [comment]
Hi @haim0n, thanks for opening an issue. We are also seeing this issue. We're working with our package hosting team to resolve the issue asap.

**Comment by martijnvans** [comment]
The fix has been merged and is awaiting rollout. Thanks for the report.
