### ISSUE TITLE
Python multiline doesn't support standard logger.exception(...) output

### ISSUE THREAD

**Issue by kyleboyle** [GoogleCloudPlatform/ops-agent#1315]
https://github.com/GoogleCloudPlatform/ops-agent/blob/0ced25cce2cf3394758b0b4f6f41f864dfa982d2/confgenerator/logging_processors.go#L57

A pretty standard way of logging an exception in an except block is to use the [logger.exception](https://docs.python.org/3/library/logging.html#logging.Logger.exception) method to log the exception at error level with the stack trace prepended with the provided message.

```python
try:
    a_result = operation1()
except:
    logger.exception(f'{self.some_context} problem with operation1')
```

resulting in something like:
```
2023-07-04 13:50:05,086 ERROR    my_app Some context problem with operation1: Traceback (most recent call last):
  File \"/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py\", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File \"/base/data/home/apps/s~nearfieldspy/1.378705245900539993/nearfieldspy.py\", line 17, in start
    return get()
  File \"/base/data/home/apps/s~nearfieldspy/1.378705245900539993/nearfieldspy.py\", line 5, in get
    raise Exception('spam', 'eggs')
    Exception: ('spam', 'eggs')
```

The line doesn't start with Traceback so it doesn't get picked up by the multiline processor.

**Comment by ridwanmsharif** [comment]
Thanks for bringing this to our attention. I'll send a PR to expand the python multiline regex to capture these cases as well.

**Comment by ridwanmsharif** [comment]
This will make it as part of the next Ops Agent release.
