### ISSUE TITLE
parse_json documentation missing config options

### ISSUE THREAD

**Issue by elsmorian** [GoogleCloudPlatform/ops-agent#1321]
**Describe the bug**
The documentation at https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/configuration#logging-processor-parse-json is lacking in mentioning options that you can use.  I stumbled upon someone else's example and discovered that you can use the `field:` option to set which field to parse as JSON from the message, which was very helpful when moving from google-fluentd

Are there any other config options missing? It would be very handy to have the ability to not remove the field you parse too for instance!

**To Reproduce**
1.Read the docs 

**Expected behavior**
The docs to mention all options you could use to configure the json_parse processor

**Comment by braydonk** [comment]
Hi @elsmorian! Thank you for bringing this oversight to our attention. We will address this docs shortcoming ASAP.

I took a look to make sure, and that is currently the only config field missing from the docs. I will discuss your suggestion about preserving the field after parsing to the team and see if it's something we'll be able to add. Thank you for opening an issue!

**Comment by jasper-elimity** [comment]
Hi @braydonk, I just stumbled across this same issue. Is there any chance of getting it reopened?
