### ISSUE TITLE
I Dont see any python sdk version that supports ops-agent installation or yaml file to install

### ISSUE THREAD

**Issue by gnsharans** [GoogleCloudPlatform/ops-agent#1498]
1. I would like to know, is there any sdk version that supports installation of ops-agent
2. Can i get an yaml file that support os policy assignment, to install ops-agent for all the supported OS.

**Comment by LujieDuan** [comment]
Hey @gnsharans, 

1. Python SDK is not required to [install the Ops Agent on individual VMs](https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/installation); if you are using the `gcloud` command, please check the [gcloud cli installation instructions](https://cloud.google.com/sdk/docs/install#installation_instructions) for the required Python version. 
2. Please check our instructions on [managing agent policies](https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/managing-agent-policies) for managing installation for a fleet of VMs; Other [installing methods](https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/install-index) are also available. 

Feel free to reopen this if further assistance is needed!

**Comment by gnsharans** [comment]
Thanks @LujieDuan.
python sdk with proper method to create ospolicy and apply ospolicy helped to resolve this.
