### ISSUE TITLE
Can't install Ops-agent on Amazon Linux 2023

### ISSUE THREAD

**Issue by huypd6946-cowell** [GoogleCloudPlatform/ops-agent#1520]
Is anyone able to install Ops-agent on Amazon Linux 2023? I have tried many methods, but none of them seem to work. Can someone support me in resolving this issue?

I want to use GCP logging to store logs on an EC2 instance running Amazon Linux 2023. Are there any alternative ways to use GCP logging if google-fluentd and Ops-agent cannot be installed?

Thanks in adavance.

**Comment by igorpeshansky** [comment]
The Ops agent does not run anywhere outside of GCE. We do not currently have an agent package that natively supports Amazon Linux 2023. You may be able to run a fluentd docker container, as suggested in https://github.com/GoogleCloudPlatform/google-fluentd/issues/428#issuecomment-1812574419.
