### ISSUE TITLE
Support referencing/overriding the traceSampled field

### ISSUE THREAD

**Issue by rpysz** [GoogleCloudPlatform/ops-agent#1558]
**Describe the bug**
Issue similar to #1483. I would like to have a possibility to propagate "traceSampled" same way as "trace" and "spanId" (or rather have a possibility to always set this field to boolean _true_, not string "true" - Google API ignores stringified values of "traceSampled" field).

**Expected behavior**
'traceSampled' field properly propagated to Google Cloud Logging as boolean type

**Environment:**
VM distro / OS: Red Hat Enterprise Linux 8 (version 8.8)
Ops Agent version: 2.44.0

**Comment by jefferbrecht** [comment]
As an alternative, would it be acceptable if the Ops Agent were to set `traceSampled=true` automatically whenever exporting a log that has `trace` or `spanId`? Or is there some other use case where you would need to be able to manually toggle `traceSampled` independently?

**Comment by rpysz** [comment]
@jefferbrecht For my solution, always setting traceSampled=true is sufficient.
