### ISSUE TITLE
Feature Request: Fetch credentials from secondary service account

### ISSUE THREAD

**Issue by abagshaw** [GoogleCloudPlatform/ops-agent#1765]
Feature Request (assuming this is not already possible):

Provide a way to configure ops agent to use a secondary service account attached to the GCE VM (instead of the default primary service account) as the identity to use when pushing logs and metrics.

This is necessary because we want the primary service account on the VM to be a service account that will _not_ have `Monitoring Metric Writer` or `Logs Writer` roles granted. This service account will be used by other applications on the host that are only able to use the primary default service account.

To allow the ops agent to continue working, we would attach a secondary service account to the GCE VM that would have `Monitoring Metric Writer` or `Logs Writer` roles granted, but we need a way to configure ops agent to use this service account instead of the default one. The docs do not suggest there is any way to do this today.

**Comment by ridwanmsharif** [comment]
You should be able to use another service account by following the instructions on this page: https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/authorization (specifically this section: https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/authorization#private_key_authorization)

It requires that you create a service account with the appropriate roles granted and then save the credentials JSON file in your VM instance. Once that is done, you need to make sure the Ops Agent is run with the `GOOGLE_APPLICATION_CREDENTIALS` env set to the credentials file.

https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/authorization#agent-creds-linux walks you though setting the env variables for the Ops Agent on linux and windows.

**Comment by igorpeshansky** [comment]
You can only have a [single service account attached to a GCE VM](https://cloud.google.com/compute/docs/access/service-accounts#serviceaccount), so, as @ridwanmsharif said, the only way to do what you're asking for is to use a private key, which is already supported.
