### ISSUE TITLE
Cleanup jmx-gatherer.jar build and inclusion

### ISSUE THREAD

**Issue by jsuereth** [GoogleCloudPlatform/ops-agent#236]
Right now, the jmx-gatherer jar is pulled in as a git submodule and built as part of ops-agent.  This has a few issues:

1. The nebula plugin is unable to read git versioning information appropriately in a submodule.  Instead we hijack its version-detection schema.  Longer term this could lead to runtime version differences (if upstream begins to use nebula-plugin for more than just git tagging).
2. We are re-building the same JAR repeatedly on different environments.  This puts a dependency on the JVM across all of our build environments, rather than just integration tests.

An ideal solution would do one of the following:

- Build the jmx-gatherer jar and publish "our" version and consume from that source.  This would allow us to carry our own patches if necessary.   The Ops-Agent built would simply point at a "released" jar to build.
- Update the submodule to work as expected with the nebula plugin.  Version should be inferred from latest commit-tag on the submodule, and all version strings we use to pull the JAR would come from that inferred tag.

**Comment by braydonk** [comment]
This seems to be obsolete.
