### ISSUE TITLE
Add support for exporting traces

### ISSUE THREAD

**Issue by lucacasonato** [GoogleCloudPlatform/ops-agent#239]
Currently the ops-agent only supports metric and log ingestion. OTLP also supports traces though (https://github.com/open-telemetry/oteps/blob/main/text/trace/0059-otlp-trace-data-format.md), and Google Cloud Operations Suite has a trace product ([Cloud Tracing](https://cloud.google.com/trace/docs)). It would be great if the ops-agent supported Jaeger/OTLP trace ingestion to Cloud Tracing.

**Comment by ridwanmsharif** [comment]
We added support for OTLP traces in version v2.31.0 See [release notes.](https://cloud.google.com/stackdriver/docs/release-notes#May_15_2023) Note that this feature is in Public Preview and so may receive updates that are not necessarily backwards compatible based on customer feedback. See how to set it up and configure it here: https://cloud.google.com/trace/docs/otlp#use-otlp-receiver

We encourage you to try it and share feedback with us.
