### ISSUE TITLE
Logging doesn’t support renaming of keys

### ISSUE THREAD

**Issue by kstephan-wescale** [GoogleCloudPlatform/ops-agent#245]
When parsing input data like
```
{
  "log": "some message",
  "time": "some timestamp"
}
```
with the `parse_json` processor, the configuration model doesn’t allow for renaming a key like “log” to “message” for GCP Logging to understand it, instead the resulting Logs Explorer entry is literal `{"log":"some.message"}`.
One could simply implement a `message_key` option as for the timestamp, but that’s rather Byzantine and useless for other or custom keys. Instead I propose to implement [fluentbit’s Modify filter](https://docs.fluentbit.io/manual/pipeline/filters/modify) and add a `filters` element to the configuration model as in #246.

**Comment by qingling128** [comment]
This is WIP

**Comment by qingling128** [comment]
CC @quentinmit for visibility

**Comment by quentinmit** [comment]
This is PR #474

**Comment by braydonk** [comment]
This is now implemented in the Ops Agent as of 2.15.0.
