### ISSUE TITLE
Support the deletion of logs to protect sensitive values.

### ISSUE THREAD

**Issue by doughepi** [GoogleCloudPlatform/ops-agent#248]
The existing, legacy, implementation of the logging agent supported log filtering for the deletion of log entries that matched a pattern. 

A feature following this issue would allow for a similar method of log processing in the new Ops Agent.

**Comment by qingling128** [comment]
Thanks for the feedback. We have released the support for this in https://github.com/GoogleCloudPlatform/ops-agent/releases/tag/2.9.0. See `exclude_logs` in the latest documentation: https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/configuration#logging-processors
