### ISSUE TITLE
Include default log rotation rules for subagent logs

### ISSUE THREAD

**Issue by yuryu** [GoogleCloudPlatform/ops-agent#251]
Subagent logs can grow quickly and fill up the disk. Currently ops agent doesn't have any logrotate rules for these log files and they continue to accumulate indefinitely.

For example, in one of the VMs I'm running, the logging-module.log file is 2.4 GB after 3 weeks. All installations will eventually run out of disk.

Users could create a rule under `/etc/logrotate.d` but a reasonable default should be provided out of the box.

**Comment by franciscovalentecastro** [comment]
The following PR `Introduce log rotation by default for self log files` https://github.com/GoogleCloudPlatform/ops-agent/pull/1102 released in Ops Agent [2.31.0](https://github.com/GoogleCloudPlatform/ops-agent/releases/tag/2.31.0) provides log rotation by default.
