### ISSUE TITLE
logName in Stackdriver to contain file name of log

### ISSUE THREAD

**Issue by iamacarpet** [GoogleCloudPlatform/ops-agent#267]
We're trying to configure the Ops Agent to include the file name of the log in the logName field in Stackdriver Logging.

For example, we want to read any logs in `/var/log/webapps/*/*.log`, where the first wildcard is the domain, the second wildcard denotes the type of log entry (it's a legacy system so can't really swap it for JSON).

This worked great with the old logging agent, as it would ingest and include the file name in the logName field:

![image](https://user-images.githubusercontent.com/1333857/141149160-d9a2ba1c-3281-49ae-b4ac-886531f4d95a.png)

We can't figure out a way to replicate this in the new Ops Agent, although StackOverflow points to a Path_Key in the native Fluent-bit config.

We'll update here if we figure it out, but in the meantime, anyone know if this is actually supported?

**Comment by franciscovalentecastro** [comment]
After the Ops Agent release `2.17.0`, there is a new feature (https://github.com/GoogleCloudPlatform/ops-agent/pull/666) called `record_log_file_path` which creates the label `agent.googleapis.com/log_file_path` with the path to the original file from which the log record was obtained. This feature works for all file based receivers (several of 3rd party app receivers fall into this category). This value was obtained from Fluent-bit's Path Key feature.

Public Documentation : https://cloud.google.com/logging/docs/agent/ops-agent/configuration#logging-receivers

**Comment by iamacarpet** [comment]
Thanks @franciscovalentecastro ,

That really is great news, really appreciate you making it happen :).

Will be sure to check it out soon & progress some of our stalled upgrades.
