### ISSUE TITLE
Custom metrics with gRPC receiver

### ISSUE THREAD

**Issue by fboismenu** [GoogleCloudPlatform/ops-agent#281]
Hello team,

Is it possible to push custom metrics via the otel collector deployed by ops agent.
It seems the otlp grpc receiver is not whitelisted …
Would be a very nice to have to be able to publish metrics with open telemetry python sdk.

Please lemme know :)
Thanks
Fred

**Comment by quentinmit** [comment]
Thanks, this use case is not possible today but we'd like to support it at some point.

**Comment by quentinmit** [comment]
We've now launched the OTLP receiver in public preview: https://cloud.google.com/monitoring/agent/ops-agent/otlp
