### ISSUE TITLE
Support for Google Container-Optimized OS

### ISSUE THREAD

**Issue by fdcds** [GoogleCloudPlatform/ops-agent#325]
It would be nice if Google Ops Agent would support Google Container-Optimized OS (https://cloud.google.com/container-optimized-os/docs).

Setting up a Google Container-Optimized OS Compute Engine instance with the legacy logging agent is extremely easy and just requires passing `google-logging-enabled=true` as metadata to the instance (https://cloud.google.com/container-optimized-os/docs/how-to/logging#creating_a_new_instance_with_the_logging_agent_enabled). I am unable to find instructions on how to enable the new Ops Agent.

**Comment by benhutchison** [comment]
The legacy logging agent is becoming.. er.. notorious ( [eg1](https://serverfault.com/questions/980569/disable-fluentd-on-on-container-optimized-os-gce/1030981#1030981) [eg2](https://serverfault.com/questions/1002309/server-crash-of-googlece-fluentd-ruby-memory-usage-high-might-be-related) [eg3](https://serverfault.com/questions/1020767/gce-stackdriver-logging-agent-fluentd-memory-leak-with-cos) ) for the high memory usage of the fluentd ruby process, which bites especially small VMs causing them to become unstable over time. Please provide this improved agent in the Container OS so we have an alternative.

**Comment by bivald** [comment]
Is there any communication regarding this, whether this is in the scope for the future? We use Cloud Monitoring for all our metrics and have spent a lot of time migrating to container optimized os, would be horrible to have to go back to another OS just to get memory and CPU stats...

**Comment by qingling128** [comment]
There is a Fluent Bit based solution in favor of the legacy logging agent for Container-optimised OS now: https://cloud.google.com/container-optimized-os/docs/how-to/logging#update_an_existing_instance_to_enable_or_disable_the_fluent-bit_agent. That should help mitigate the high memory usage issue.

**Comment by AndrewDryga** [comment]
There is a bug with breaks logging on new FluentBit agent: https://issuetracker.google.com/issues/285950891

**Comment by jelling** [comment]
This issue seems like a straight forward and important question:  how do we make the new Google created logging agent work with the new Google created container image?

Perhaps it's not possible. But two years is an awfully long time to let such a ticket sit open with no official response.

**Comment by pdfrod** [comment]
For me logging works well enough already on COS. What doesn't work is RAM and disk capacity metrics; as far as I can tell there isn't any way to get that working on COS at the moment. If the OpsAgent won't be supported on COS, then how will we be able to get those metrics?

**Comment by sato-s** [comment]
👍 for @pdfrod 
This issue should be re-opened.

**Comment by artemshchirov** [comment]
👍 for @pdfrod
This issue should be re-opened.

**Comment by egorkosaretsky** [comment]
👍 for @pdfrod
This issue should be re-opened.
