### ISSUE TITLE
docs: runtime service and account/permission requirements?

### ISSUE THREAD

**Issue by remoe** [GoogleCloudPlatform/ops-agent#338]
What are the base runtime requirements (google config, services) for this agent?

- Does it require the default GCP service-account ? When yes, is there any minimal instruction to setup this for this agent ?
- Does it need to run other google agents/services ?
- Does it required preconfigured files on the filesystem ?

It should be possible to run this agent without any "default" large preconfigured VM image?

I found some issues here: https://github.com/GoogleCloudPlatform/ops-agent/issues/334

**Comment by remoe** [comment]
Here is my minimal sample to allow show GCP metrics on a system with small cpu/memory resources:

https://github.com/remoe/gcp-fcos-agent

**Comment by igorpeshansky** [comment]
The Ops agent is documented at https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/. All of your questions ought to be answered there, including the list of supported OS distributions. If that documentation is unclear or insufficient, please use the "Send feedback" button directly on the documentation pages, so it will be seen by our docs team. Thanks.
