### ISSUE TITLE
Unable to split syslog to different to different logger name

### ISSUE THREAD

**Issue by fbiagio** [GoogleCloudPlatform/ops-agent#362]
Hi, 
I'm trying to update google-fluentd-agent with this new one for logging on custom rhel VM into cloud logging 

logs are send with rsyslog to a local socket that was managed by osp-agent 

`cat /etc/google-cloud-ops-agent/config.yaml
logging:
  receivers:
    syslog:
      type: syslog
      transport_protocol: udp
      listen_host: 127.0.0.1
      listen_port: 1514
   service:
    pipelines:
      default_pipeline:
        receivers: [syslog]
`

The old agent configuration allow us to split out of the box the logs into different target log_name  based on facility and severity 

{
insertId: "irv8zjee248rhz8o4"
labels: {
compute.googleapis.com/resource_name: "XXXXXXXXXXXXXXXXX"
}
logName: "projects/pXXXXXXXXXXXXXXXXX/logs/**syslog.user.notice**"
receiveTimestamp: "2022-01-26T15:11:41.338528447Z"
resource: {
labels: {
instance_id: "1063345352058620069"
project_id: "XXXXXXXXXXXXXXXXX"
zone: "europe-west3-b"
}
type: "gce_instance"
}
textPayload: "Jan 26 16:11:37 XXXXXXXXXXXXXXXXX subscription-manager[2592720]: Added subscription for 'Content Access' contract 'None'"
timestamp: "2022-01-26T15:11:37.662227345Z"
}

The new agent is able to send all data but messages lose information about facility and use a default log_name (syslog) in cloud logging

{
insertId: "e5fwsug1qxxo7v"
jsonPayload: {
message: "<14>Jan 26 14:49:32 YYYYYYYYYYYYYYY root[285447]: testmessagetakke"
}
logName: "projects/YYYYYYYYYYYYYYY **/logs/syslog**"
receiveTimestamp: "2022-01-26T13:49:33.487331005Z"
resource: {
labels: {
instance_id: "1412765332707494911"
project_id: "YYYYYYYYYYYYYYY "
zone: "europe-west3-a"
}
type: "gce_instance"
}
timestamp: "2022-01-26T13:49:32.854706758Z"
}

Is there a way to split them?

**Comment by quentinmit** [comment]
We're working on PR #474 and a followup PR to add the ability to set the log name using any of the fields in a log entry.

**Comment by quentinmit** [comment]
That PR is now merged and you should be able to use the `modify_fields` processor to change the log name.
