### ISSUE TITLE
Types parameter not available in parse_regex

### ISSUE THREAD

**Issue by tfspire** [GoogleCloudPlatform/ops-agent#367]
Hi,

I'm trying to migrate from the legacy google agent to the new ops-agent a regex parser.

In the legacy agent, it was possible to define the `types` parameter to change the type of the values captured, I can see that this is also available in fluentbit but I couldn't find this parameter available on the ops-agent configuration.

Is this types parameter not available on the ops-agent for the type regex_parser? If that's the case, any way of workaround to have this configured?

Thanks

**Comment by quentinmit** [comment]
To change the type of a field, use the `modify_fields` processor after `parse_regex`. See https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/configuration#logging-processor-modify-fields
