### ISSUE TITLE
Ability to include multiple configuration files

### ISSUE THREAD

**Issue by samveen** [GoogleCloudPlatform/ops-agent#428]
As a part of our deployments we have different components on each of our GCE instances. Instead of making changes to the configuration file `/etc/google-cloud-ops-agent/config.yaml` , I would like the ability to drop a configuration file for the receiver associated with each component into a directory, for example `/etc/google-cloud-ops-agent/config.d/${COMPONENT_RECEIVER_YAML}`

The existing structure of how configuration is built already combines the built in configuration with the additional configuration as stored in `/etc/google-cloud-ops-agent/config.yaml`, I expect that the ability to merge 3rd and further additional configurations should not be a stretch.

I'll see if I can rustle up a merge request for it, but given my lack of exposure to `golang`, that'll definitely take a long while.

**Comment by caseyduquettesc** [comment]
https://github.com/GoogleCloudPlatform/ops-agent/issues/265

**Comment by samveen** [comment]
@caseyduquettesc Thank you for that cross-reference. 

This issue can  be closed as it is a duplicate of #265 .
