### ISSUE TITLE
centos + couchdb 3rd party app test is failing

### ISSUE THREAD

**Issue by martijnvans** [GoogleCloudPlatform/ops-agent#434]
output is like:

        + sudo yum-config-manager --add-repo https://couchdb.apache.org/repo/couchdb.repo
        + sudo yum install -y couchdb
        Importing GPG key 0x7A00258D:
         Userid     : "The Apache Software Foundation (Package repository signing key) <root@apache.org>"
         Fingerprint: 390e f70b b1ea 12b2 7739 6295 0ee6 2fb3 7a00 258d
         From       : https://couchdb.apache.org/repo/keys.asc
        warning: /var/cache/yum/x86_64/7/couchdb/packages/couch-js-1.8.5-21.el7.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID 9657a78e: NOKEY
        warning: /var/cache/yum/x86_64/7/couchdb/packages/couchdb-3.2.1-2.el7.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 232ef177: NOKEY
        Importing GPG key 0x7A00258D:
         Userid     : "The Apache Software Foundation (Package repository signing key) <root@apache.org>"
         Fingerprint: 390e f70b b1ea 12b2 7739 6295 0ee6 2fb3 7a00 258d
         From       : https://couchdb.apache.org/repo/keys.asc
        Importing GPG key 0x9657A78E:
         Userid     : "Nicolae Vatamaniuc <vatamane@apache.org>"
         Fingerprint: 0bd7 a984 99c4 ab41 c910 ee65 fc04 dfbc 9657 a78e
         From       : https://couchdb.apache.org/repo/rpm-package-key.asc
        
        
        Public key for couchdb-3.2.1-2.el7.x86_64.rpm is not installed
        
        
         Failing package is: couchdb-3.2.1-2.el7.x86_64
         GPG Keys are configured as: https://couchdb.apache.org/repo/keys.asc, https://couchdb.apache.org/repo/rpm-package-key.asc

Full log: https://storage.cloud.google.com/ops-agents-public-buckets-test-logs/prod/stackdriver_agents/testing/consumer/third_party_apps/presubmit_github/centos7/141/20220301-113150/logs/%2Bbuild_and_test.txt

**Comment by dehaansa** [comment]
Nothing obvious. No new releases. Key ID called out in [the install docs](https://docs.couchdb.org/en/stable/install/unix.html#gpg-keys-used-for-signing-the-couchdb-repositories) looks to be that first Apache package signing key (0x7A00258D).

**Comment by martijnvans** [comment]
thanks for taking a look. maybe we should check back in a while to see if they fix it on their end then.

**Comment by sophieyfang** [comment]
This is still occurring. I think we shall look for another reliable repo for installing couchdb @dehaansa  WDYT? :)

**Comment by dehaansa** [comment]
This should be resolved currently in integration tests, and couchdb was also very responsive in fixing the GPG key so the situation should be fully resolved when https://github.com/GoogleCloudPlatform/ops-agent/pull/450 is merged.
