### ISSUE TITLE
AlmaLinux OpsAgent Installation

### ISSUE THREAD

**Issue by metacogni** [GoogleCloudPlatform/ops-agent#453]
Trying to install Ops Agent on **AlmaLinux/CloudLinux** but getting:

```
Traceback (most recent call last):
  File "mass-provision-google-cloud-ops-agents.py", line 17, in <module>
    import dataclasses
ModuleNotFoundError: No module named 'dataclasses'
```

Aware of supported OS but often what works with Rocky Linux (_and other binary-compatible distros_) works with AlmaLinux.

Has anyone succeeded in getting this to work with AlmaLinux/CL?

**Comment by sophieyfang** [comment]
Are you trying install ops-agent across multiple VMs? That mass-provision python script needs python3. If you only need to install ops-agent https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/installation#install-latest-version on single VM, you can follow this instruction: https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/installation#install-latest-version

**Comment by metacogni** [comment]
Thank you so much, @sophieyfang 

Can't believe I didn't think about this.

You  can't believe the time you just saved me.

While the Observability window is still reporting "**Requires Ops Agent**" and the option to "**Install**" even after restarting and checking status to confirm that the service bus active, I can start prepping the Terraform for the other VMs now that you have guided me true.

Thanks a ton!

**Comment by sophieyfang** [comment]
You are really welcome:)
 If VM dashboard in Pantheon is the Observability windows you meant, after installing ops-agent it has some latency and it takes sometime to show the active status of ops-agent on VM dashboard

**Comment by metacogni** [comment]
Thanks, Sophie.

Not Pantheon though.

It is a permission issue and getting that corrected.
