### ISSUE TITLE
Add support for logging.googleapis.com/spanId field

### ISSUE THREAD

**Issue by nonokangwei** [GoogleCloudPlatform/ops-agent#459]
Support the JSON payload that with logging.googleapis.com/spanId field which will mapping to the spanID field of logentry.

**Comment by andreswebs** [comment]
same for the logging.googleapis.com/trace_sampled field, which should map to the traceSampled field of the LogEntry

as was the case for the legacy logging agent:

https://cloud.google.com/logging/docs/agent/logging/configuration#special-fields

**Comment by braydonk** [comment]
@andreswebs has graciously offered to contribute the support for this! We will keep this ticket updated with progress. There are some PRs that will need to be made to Fluent Bit first, then a PR here once we pick those changes up on our side.

**Comment by andreswebs** [comment]
@braydonk Hello! I believe this can be closed?
