### ISSUE TITLE
Add support to customize port number for agent metrics

### ISSUE THREAD

**Issue by pandrian** [GoogleCloudPlatform/ops-agent#461]
Any chance we will be able to change the port or change it to something that is not conflicting?
https://github.com/GoogleCloudPlatform/ops-agent/blob/master/confgenerator/agentmetrics.go#L36

As one of the Druid components uses port 8888 and its conflicting with ops-agent

`Mar 10 13:08:21 otelopscol: 2022-03-10T13:08:21.717Z#011error#011service/collector.go:153#011Asynchronous error received, terminating process#011{"error": "listen tcp :8888: bind: address already in use"}`

**Comment by braydonk** [comment]
Hi @pandrian, I am currently working on changing our usage of port 8888 to something different; it's a popular port not just with Apache Druid but with some other popular applications as well. I will mention this issue when I get that PR open. Thanks for making an issue!

**Comment by pandrian** [comment]
@jefferbrecht Many thanks for this change!
