### ISSUE TITLE
mysql error 

### ISSUE THREAD

**Issue by martijnvans** [GoogleCloudPlatform/ops-agent#467]
The following failed, 4 times in a row: 

```
+ sudo apt-key adv --keyserver [pgp.mit.edu](https://www.google.com/url?q=http://pgp.mit.edu&sa=D) --recv-keys 3A79BD29
Warning: apt-key output should not be parsed (stdout is not a terminal)
gpg: keyserver receive failed: No keyserver available
```

https://storage.cloud.google.com/ops-agents-public-buckets-test-logs/prod/stackdriver_agents/testing/consumer/third_party_apps/presubmit_github/buster/232/20220314-092454/logs/%2Bbuild_and_test.txt

Not sure if it is a transient issue or something we need to fix, or both.

**Comment by martijnvans** [comment]
From @dehaansa: I think mysql has had trouble reaching that PGP key server for a long time, I have checked back every week or two and it's always seemed to be down, without anyone on the internet seeming to know anything about it. Solution might be just to disable the GPG check, even though that's not ideal.

**Comment by dehaansa** [comment]
I've went to double check after sending that to Martijn in chat, and I can access it from my personal laptop. Will see if I can tinker with a GCP instance and figure something out. 

https://pgp.mit.edu/pks/lookup?op=vindex&search=0x467B942D3A79BD29
