### ISSUE TITLE
How to disable metric collection?

### ISSUE THREAD

**Issue by legal90** [GoogleCloudPlatform/ops-agent#574]
Hi! 
I'm sorry for opening the new issue, but I didn't find the answer on my question in docs or in any other issues here.

I want to run Ops Agent only for Logging purposes. I don't need metrics to be collected from my GCE instance. How can I disable the `metrics` part of the Ops Agent completely?

I'm trying this config, but it doesn't help:
```
# /etc/google-cloud-ops-agent/config.yaml
# <...>
metrics:
  processors:
    metrics_filter:
      type: exclude_metrics
      metrics_pattern: ["agent.googleapis.com/*"]
  service:
    pipelines:
      default_pipeline:
        receivers: []
        processors: []
        exporters: []
```

## How I validate:  
My GCE instance doesn't have the role `roles/monitoring.metricWriter`, so I see these messages in syslog:
```
May  3 12:00:06 vm-24-euw1-c9p1 otelopscol[1053890]: 2022-05-03T12:00:06.431Z#011error#011collector@v0.26.1-0.20220307211504-dc45061a44f9/metrics.go:235#011could not export time series to GCM#011{"error": "rpc error: code = PermissionDenied desc = Permission monitoring.timeSeries.create denied (or the resource may not exist)."}
May  3 12:00:06 vm-24-euw1-c9p1 otelopscol[1053890]: github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/collector.(*MetricsExporter).exportPendingTimeSerieses
May  3 12:00:06 vm-24-euw1-c9p1 otelopscol[1053890]: #011/root/go/pkg/mod/github.com/!google!cloud!platform/opentelemetry-operations-go/exporter/collector@v0.26.1-0.20220307211504-dc45061a44f9/metrics.go:235
May  3 12:00:06 vm-24-euw1-c9p1 otelopscol[1053890]: github.com/GoogleCloudPlatform/opentelemetry-operations-go/exporter/collector.(*MetricsExporter).exportTimeSeriesRunner
May  3 12:00:06 vm-24-euw1-c9p1 otelopscol[1053890]: #011/root/go/pkg/mod/github.com/!google!cloud!platform/opentelemetry-operations-go/exporter/collector@v0.26.1-0.20220307211504-dc45061a44f9/metrics.go:103
```
I want the metric collection to be disabled, so it won't even try to push them anywhere. 
Could you please suggest the right configuration for that? Thank you!

P.s. Ideally, it would be good if `google-cloud-ops-agent-opentelemetry-collector` won't run at all.

**Comment by sophieyfang** [comment]
otel part of ops-agent can't be turned off completely. You can disable it to not send hostmetrics, it's still there to send out agent self metrics, e.g. agent/uptime： https://cloud.google.com/monitoring/api/metrics_opsagent#agent-agent. Agent metrics is free.

**Comment by legal90** [comment]
Thank you, @sophieyfang!
Could you please suggest, how the metrics config should look in this case?

**Comment by legal90** [comment]
I tried using the same configuration which I mentioned in the first message and also added the role `roles/monitoring.metricWriter` to the instance's service account and now the error message is gone. 

Also, it seems that only free agent metrics are sent to Google with that config. Thank you!
