### ISSUE TITLE
Fresh install failing to send default metrics

### ISSUE THREAD

**Issue by SteadBytes** [GoogleCloudPlatform/ops-agent#584]
Installation of ops-agent as per https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/installation#gce-ui-install on a RHEL 8 VM succeeded without errors, however the ops-agent is not detected in the cloud console and the following errors are present in the systemd logs:

```
 otelopscol[1055]:         /root/go/pkg/mod/github.com/!google!cloud!platform/opentelemetry-operations-go/exporter/collector@v0.26.1-0.20220307211504-dc45061a44f9/metrics.go:1031
May 06 23:33:31 otelopscol[1055]: 2022-05-06T23:33:31.616Z        error        collector@v0.26.1-0.20220307211504-dc45061a44f9/metrics.go:235        could not export time series to GCM        {"error": "rpc error: code = InvalidArgument desc = Name must begin with '{resource_container_type}/{resource_container_id}', got: projects/"}
```

No additional configuration is in-place, this is immediately after the installation without further customisation.  Is there some configuration that may be needed or are the default metrics invalid somehow?

Thanks 😄

**Comment by igorpeshansky** [comment]
Thanks for the report. We need more information to continue the investigation. Your installation method implies that this is a GCE VM. What version of the agent was installed? How is the agent authenticated/authorized? Are there any other messages from `otelopscol` in the system logs?

Note that we can only perform a general investigation from a GitHub issue. If we end up needing to look at your specific setup (e.g., cloud project,), we would have to do that via a cloud support case. That is also the best way to ensure you're kept apprised of the status of the investigation — any updates on GitHub will be best-effort. Are you in a position to open one?

**Comment by SteadBytes** [comment]
Thanks for the reply, I will open a support case.

For reference:

- GCE VM
- Ops agent v2.15.0-1
- Authz via the compute engine service account
- No other log messages of interest, just repeated occurrences of the error above
