### ISSUE TITLE
active_directory_ds twice defined log_name

### ISSUE THREAD

**Issue by sophieyfang** [GoogleCloudPlatform/ops-agent#585]
Trying to understand why the same log_name got defined twice except for the log_name, other field though name is the same but the value slightly differs, i can only guess it's intended to test more.  This causes duplicating the contents in our side..

TODO: We will add a validation check soon to avoid duplicate metrics name and log name.
Hi Brandon :) @BinaryFissionGames,
In the meanwhile, could you submit a PR to deduplicate the log_name, i am not sure which one we shall keep, as you implement this integration, i will leave it up to you. Thanks!

https://github.com/GoogleCloudPlatform/ops-agent/blob/daac0f845adb9b6b2ec943aa962673c8361602d6/integration_test/third_party_apps_data/applications/active_directory_ds/metadata.yaml#L78

**Comment by BinaryFissionGames** [comment]
As you noted, the other case was added for extra testing (the receiver listens on 2 channels, so the test is to make sure that messages are received on BOTH windows event log channels).

I've submitted a PR removing the less important test, #586.
