### ISSUE TITLE
 Not able to start ops agent service when use exclude_logs. 

### ISSUE THREAD

**Issue by saeedgenmills** [GoogleCloudPlatform/ops-agent#606]
Is exclude_logs  parser supported in google ops agent ?

Getting below error in journalcrl -xe.

-- Unit google-cloud-ops-agent-opentelemetry-collector.service has begun starting up.
May 12 03:34:39 server2 google_cloud_ops_agent_engine[2537455]: 2022/05/12 03:34:39 The agent config file is not valid. Detailed error: logging processor with type "exclude_logs" is not supported. Supported logging processor types: [apache_access, apache_error, cassandra_debug, cassandra_gc, cassandra_system, mysql_error, mysql_general, mysql_slow, nginx_access, nginx_error, parse_json, parse_regex, redis].
May 12 03:34:39 server2 google_cloud_ops_agent_engine[2537453]: 2022/05/12 03:34:39 The agent config file is not valid. Detailed error: logging processor with type "exclude_logs" is not supported. Supported logging processor types: [apache_access, apache_error, cassandra_debug, cassandra_gc, cassandra_system, mysql_error, mysql_general, mysql_slow, nginx_access, nginx_error, parse_json, parse_regex, redis].
May 12 03:34:39 server2 systemd[1]: google-cloud-ops-agent.service: Control process exited, code=exited status=1
May 12 03:34:39 server2 systemd[1]: google-cloud-ops-agent.service: Failed with result 'exit-code'.

Please fine low content of log files.

logging:
  receivers:
    cronlogs:
      type: files
      include_paths:
      - /var/log/cron
    securelogs:
      type: files
      include_paths:
      - /var/log/secure
    saltlogs:
      type: files
      include_paths:
      - /var/log/salt/minion
    abccheckerlogs:
      type: files
      include_paths:
      - /var/log/abcchecker.log

  processors:
    abc_default:
      type: parse_regex
      regex: (?<exclude>abc|axz)
    sapdefault:
      type: exclude_logs
      match_any:
      - '(jsonPayload.message =~ "log spam 1")'

  service:
    pipelines:
      abcsys_pipeline:
        receivers:
         - cronlogs
         - securelogs
         - saltlogs
        processors:
         - abc_default
      saplog_pipeline:
        receivers:
         - abccheckerlogs
        processors:
         - sapdefault

**Comment by saeedgenmills** [comment]
May 12 03:34:39 server2 google_cloud_ops_agent_engine[2537455]: 2022/05/12 03:34:39 The agent config file is not valid. Detailed error: logging processor with type "exclude_logs" is not supported. Supported logging processor types: [apache_access, apache_error, cassandra_debug, cassandra_gc, cassandra_system, mysql_error, mysql_general, mysql_slow, nginx_access, nginx_error, parse_json, parse_regex, redis].

**Comment by saeedgenmills** [comment]
as per log "exclude_logs" parser is not supported.

**Comment by quentinmit** [comment]
You need to upgrade your Ops Agent to a version that includes `exclude_logs`. It was first added in version 2.9.0, I believe. What version do you have installed now?

**Comment by ridwanmsharif** [comment]
Was not able to reproduce. At pointed out in https://github.com/GoogleCloudPlatform/ops-agent/issues/606#issuecomment-1126407829, it may have been because an older version of the agent was being used that didn't yet have this processor. 

If you're able to reproduce this issue again with a version greater than 2.9.0, please re-open this issue.
