### ISSUE TITLE
Add Ops Agent support for RHEL 9 (Plow)

### ISSUE THREAD

**Issue by danielkubat** [GoogleCloudPlatform/ops-agent#638]
Please add Ops Agent support for RHEL 9 (Plow).

- RHEL 9 is not listed in https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent#supported_operating_systems
- `google-cloud-ops-agent-el9` is not available in https://packages.cloud.google.com/yum/repos/

**Comment by 20100959** [comment]
création des issues chez google : 
https://issuetracker.google.com/issues/247952795
https://issuetracker.google.com/issues/247939268

**Comment by chrisahl** [comment]
Any ETA on when this will be implemented?

**Comment by sophieyfang** [comment]
We are still prioritizing this work in our end. Once, it's released, you shall see it in our public doc page: https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent#supported_operating_systems

**Comment by orbiq** [comment]
Dear all,
thumbs up to have this agent supported in Centos 9 Stream Google Cloud VM.

**Comment by sffc** [comment]
I'm surprised that having ops agent support isn't a prerequisite for listing the image in GCE. This is now blocking migration to Rocky Linux 9

**Comment by qingling128** [comment]
Thank you so much for all the feedback. Rhel 9 has been prioritized and actively worked on. We are also exploring ways to improve this process. Stay tuned!

**Comment by qingling128** [comment]
Internal trackers: b/235589598 and b/265457951

**Comment by philip-harvey** [comment]
I too am shocked that an image can go GA without agent support.  We standardized on Rocky9 for GCP deployments and have just found that Rocky9 doesn't work correctly in GCE due to lack of agent support.  Hoping this can be resolved urgently.  Should we open a Sev2 support case to give this some urgency?

**Comment by qingling128** [comment]
Hi @philip-harvey, thank you for your report as well. Customer support cases do generally help justify prioritization. For this specific case, we are actively working on adding the support for Rocky9, and it's a top priority.

It does still help justify the priority to improve this process in the future (e.g. ensure the agent support is in place before a GCE image is ready). In case you are planning to file a customer case, it would be very useful to include the business impact for prioritization references.

**Comment by philip-harvey** [comment]
Support case created. 43130169

**Comment by danielkubat** [comment]
Support case #43136943 (we are now waiting since 5/2022..)

**Comment by hoexter** [comment]
Created 43009413 two weeks ago and was redirected here for further updates.

**Comment by chrisahl** [comment]
It's been 4 months since I asked for an ETA so was wondering if there is any update on when this might be addressed?

**Comment by qingling128** [comment]
Hi,

Thank you for the patience. We are continuing to actively work on RHEL9 support.

Some related PRs:
* https://github.com/GoogleCloudPlatform/ops-agent/pull/1106 addressed the verification processes for third party app integration support.
* https://github.com/GoogleCloudPlatform/ops-agent/pull/1123 officially enabled rhel 9 in the routine release validation process 

This is still a top priority for us. And right now we are going through some internal final validation to see if everything looks good. Stay tuned.

**Comment by igorpeshansky** [comment]
RHEL 9 is supported as of the [2.27.0](https://github.com/GoogleCloudPlatform/ops-agent/releases/tag/2.27.0) release.
